homework3
SlavikkUS/Homework pull request #4
Opened 2024-09-19 21:32 UTC by SlavikkUS

2024-09-20 08:27 UTC, PavelIvanouski requested changes

2024-09-20 08:27 UTC, PavelIvanouski commented on src/by/it_academy/practice/homework3/Homework3.java
> +        Scanner scanner = new Scanner(System.in);
лучше сканер использовать в каждом задании, чтоыб на каджое задание свое число было введено

2024-09-20 08:27 UTC, PavelIvanouski commented on src/by/it_academy/practice/homework3/Homework3.java
> +        if ((number1 % 2 == 0) && (number2 % 2 == 0) && (number3 % 2 == 0)) {
как-то много проверок)
можно успростить - просто проверять каждую цифру отдельно

2024-09-20 08:27 UTC, PavelIvanouski commented on src/by/it_academy/practice/homework3/Homework3.java
> +                System.out.println(Month.DECEMBER + " - is a winter season");
может укоротить код с помощью -> ? (один из вариантов switch)

2024-09-20 19:35 UTC, SlavikkUS commented on src/by/it_academy/practice/homework3/Homework3.java
> +                System.out.println(Month.DECEMBER + " - is a winter season");
У меня просто JDK 11  стоит , такой метод поддерживается с 14('switch' expressions are not supported at language level '11') выдает

2024-09-22 09:34 UTC, PavelIvanouski requested changes

2024-09-22 09:34 UTC, PavelIvanouski commented on src/by/it_academy/practice/homework3/Homework3.java
> +        System.out.println(findPrimeNumbers());
тут можно по аналогии с findDegreeNumbers() просто вызвать метод findPrimeNumbers - пускай в методе вывод на консоль будет, а не System.out.println(findPrimeNumbers()); в main методе

2024-09-22 09:34 UTC, PavelIvanouski commented on src/by/it_academy/practice/homework3/Homework3.java
> +        System.out.print("Введите число, а мы проверил четность введённых цифр:");
сканер и проверку корректного ввода можно вынести в отдельные методы и их вызывать

2024-09-23 07:13 UTC, PavelIvanouski requested changes

2024-09-23 07:13 UTC, PavelIvanouski commented on src/by/it_academy/practice/homework3/Homework3.java
> +            } else
зачем тут else? просто в конце нужно вывести чему равно sum

2024-09-23 07:13 UTC, PavelIvanouski commented on src/by/it_academy/practice/homework3/Homework3.java
> +        System.out.print("Введите целое трехзначное число: ");
в main не должно быть sout вызовов. только вызовы методов с решением задач
например
findPrimeNumbers(findNumbers());
findDegreeNumbers(findNumbers());
findSymmetryFirstAndLastNumbers();
 findRealTriangle();

2024-09-23 08:59 UTC, PavelIvanouski approved these changes

2024-09-23 10:02 UTC, merged